consts = {
	'CLIENT_NAME' : "pytorrent",
	'CLIENT_ID' : "PY",
	'CLIENT_VERSION' : "0001",

	'PEER_PORT' : 1234,
	'TRACKER_PORT' : 8080,
	'TRACKER_RETRY_TIME' : 1,

	'PIECE_LENGTH' : 524288,
	'BLOCK_LENGTH' : 16384,

	'PEER_HEARTBEAT' : 30,
	'PEER_DOWNLOAD_LIMIT' : 5,
	'MAX_UNCHOKED_PEER' : 4,

	'SELECT_BEST_PEERS_TIME' : 10,
	'SELECT_OPTIMISTICALLY_TIME' : 30
}